name = "meridian-app-july"
compatibility_date = "2024-08-26"
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_date = "2024-08-26"

[env.preview]
compatibility_date = "2024-08-26"

# Runtime variables
[vars]
# sandbox | live
PAYPAL_ENV = "live"

# R2 bucket bindings (optional)
[[r2_buckets]]
binding = "PAYPAL_LOGS"
bucket_name = "meridian-dr"

# Cloudflare Pages configuration
[[pages.rules]]
source = "/api/*"
destination = "/api/:path*"

# Environment variables (set these in Cloudflare dashboard)
# DATABASE_URL = ""
# NEXTAUTH_SECRET = ""
# NEXTAUTH_URL = ""
# STRIPE_SECRET_KEY = ""
# STRIPE_WEBHOOK_SECRET = ""
# EMAIL_SERVER_HOST = ""
# EMAIL_SERVER_PORT = ""
# EMAIL_SERVER_USER = ""
# EMAIL_SERVER_PASSWORD = ""
# DR_CEDULA_API_URL = ""

# Build configuration
[build]
command = "npx @cloudflare/next-on-pages@1"
cwd = "."

# Node.js compatibility for serverless functions
compatibility_flags = ["nodejs_compat"]

# Limits
[limits]
cpu_ms = 50000
