name = "paypal-worker"
main = "src/index.ts"
compatibility_date = "2024-08-26"
compatibility_flags = ["nodejs_compat"]

[vars]
PAYPAL_ENV = "live"

[[r2_buckets]]
binding = "PAYPAL_LOGS"
bucket_name = "meridian-dr"
